/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.abc.gui;

import com.abc.model.ScaledImage;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author nipun
 */
public class LoginAndSignup extends MainPanel {

    private JPanel bgPanel;
    private JPanel floatingPanel;

    /**
     * Creates new form LoginAndSignup
     *
     * @param content
     */
    public LoginAndSignup(JPanel content) {
        super(content.getClass());
        initComponents();
        setLayout(new BorderLayout());
        setBackgroundPanel();
        setFloatingPanel(content);
    }

    public final void setFloatingPanel(JPanel content) {
        floatingPanel = content;
        floatingPanel.setOpaque(false);
        floatingPanel.setBackground(new Color(0, 0, 0, 150));

        bgPanel.setLayout(new GridBagLayout());
        bgPanel.add(floatingPanel, new GridBagConstraints());
    }

    private void setBackgroundPanel() {
        BufferedImage bImg = null;
        try {
            bImg = ImageIO.read(LoginAndSignup.class.getResourceAsStream("../assets/img/login&signup-bg.jpeg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        ScaledImage img = new ScaledImage("login&signup-bg", bImg);

        bgPanel = new ImagePanel(this, img);
        this.add(bgPanel, BorderLayout.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
