/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.abc.gui;

/**
 *
 * @author nipun
 */
public class UpperPanel extends javax.swing.JPanel {

    /**
     * Creates new form upperPanel
     */
    public UpperPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperLeftPanel = new javax.swing.JPanel();
        upperRightPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 40));
        setLayout(new java.awt.BorderLayout());

        upperLeftPanel.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout upperLeftPanelLayout = new javax.swing.GroupLayout(upperLeftPanel);
        upperLeftPanel.setLayout(upperLeftPanelLayout);
        upperLeftPanelLayout.setHorizontalGroup(
            upperLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        upperLeftPanelLayout.setVerticalGroup(
            upperLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(upperLeftPanel, java.awt.BorderLayout.LINE_START);

        upperRightPanel.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout upperRightPanelLayout = new javax.swing.GroupLayout(upperRightPanel);
        upperRightPanel.setLayout(upperRightPanelLayout);
        upperRightPanelLayout.setHorizontalGroup(
            upperRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        upperRightPanelLayout.setVerticalGroup(
            upperRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(upperRightPanel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel upperLeftPanel;
    private javax.swing.JPanel upperRightPanel;
    // End of variables declaration//GEN-END:variables
}
