/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.abc.gui;

import com.abc.model.ScaledImage;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author nipun
 */
public class Welcome extends MainPanel {

    private JPanel bgPanel;
    private JPanel floatingPanel;

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        super(Welcome.class);
        initComponents();
        this.setLayout(new BorderLayout());
        setBackgroundPanel();
        setFloatingPanel();
    }

    private void setFloatingPanel() {

        floatingPanel = new WelcomeContent();
        floatingPanel.setOpaque(false);
        floatingPanel.setBackground(new Color(0, 0, 150, 90));

        bgPanel.setLayout(new GridBagLayout());
        bgPanel.add(floatingPanel, new GridBagConstraints());
    }

    private void setBackgroundPanel() {
        BufferedImage bImg = null;
        try {
            bImg = ImageIO.read(Welcome.class.getResourceAsStream("../assets/img/welcome-bg.jpeg"));
        } catch (IOException e) {
        }
        
        ScaledImage img = new ScaledImage("welcome-bg", bImg);
        
        bgPanel = new ImagePanel(this, img);
        this.add(bgPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();

        setPreferredSize(new java.awt.Dimension(1200, 750));

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
